import {readdir,readFile,writeFile,mkdir,cp} from 'node:fs/promises';
import {join,dirname} from 'node:path';
const root=process.cwd(),out=join(root,'_site');
const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const inline=s=>s.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img src="$2" alt="$1" loading="lazy">').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');
function parse(md){const lines=md.trim().split(/\r?\n/),html=[];let list=false,code=false,buf=[];const flush=()=>{if(buf.length){html.push(`<p>${inline(buf.join(' '))}</p>`);buf=[]}};for(const line of lines){if(line.startsWith('```')){if(code){html.push(`<pre><code>${esc(buf.join('\n'))}</code></pre>`);buf=[];code=false}else{flush();if(list){html.push('</ul>');list=false}code=true}continue}if(code){buf.push(line);continue}if(!line.trim()){flush();if(list){html.push('</ul>');list=false}continue}const h=line.match(/^(#{2,3})\s+(.+)/);if(h){flush();const level=h[1].length,id=h[2].toLowerCase().replace(/[^\w\u4e00-\u9fff]+/g,'-');html.push(`<h${level} id="${id}">${inline(h[2])}</h${level}>`);continue}if(line.startsWith('- ')){flush();if(!list){html.push('<ul>');list=true}html.push(`<li>${inline(line.slice(2))}</li>`);continue}if(line.startsWith('> ')){flush();html.push(`<blockquote>${inline(line.slice(2))}</blockquote>`);continue}buf.push(line)}if(code)html.push(`<pre><code>${esc(buf.join('\n'))}</code></pre>`);else flush();if(list)html.push('</ul>');return html.join('\n')}
function front(raw){const m=raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);if(!m)return [{},raw];const meta={};m[1].split('\n').forEach(l=>{const i=l.indexOf(':');if(i>0)meta[l.slice(0,i).trim()]=l.slice(i+1).trim()});return [meta,m[2]]}
function page(meta,body){const heads=[...body.matchAll(/<h2 id="([^"]+)">([^<]+)<\/h2>/g)];const toc=heads.map(x=>`<a href="#${x[1]}">${x[2]}</a>`).join('');return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${meta.description||meta.title}"><title>${meta.title} · Embodied Forge</title><link rel="stylesheet" href="../../styles.css"></head><body><header><div class="wrap nav"><a class="brand" href="../../"><span>EF</span><div><b>EMBODIED FORGE</b><small>BY TALOSHUA</small></div></a><button class="menu">☰</button><nav><a href="../../#projects">项目</a><a href="../../#knowledge">知识库</a><a href="../../#insights">论文与教程</a><a href="https://github.com/TalosHua">GitHub</a></nav></div></header><main class="article-shell wrap"><div class="article-head"><a class="back" href="../../">← 返回首页</a><div class="article-kicker">${meta.type||'NOTE'} · ${meta.status||'持续更新'}</div><h1>${meta.title}</h1><p class="article-deck">${meta.description||''}</p><div class="article-meta"><span>${meta.date||'2026-09-07'}</span><span>${meta.tags||''}</span><span>约 ${Math.max(3,Math.ceil(body.length/900))} 分钟阅读</span></div></div><div class="article-layout"><aside class="toc"><b>本页目录</b>${toc}</aside><article class="prose">${body}</article></div></main><footer><div class="wrap"><a class="brand" href="../../"><span>EF</span><div><b>EMBODIED FORGE</b></div></a><p>Robotics · Learning · Real-world Systems</p><small>© 2026 TalosHua</small></div></footer><script src="../../app.js"></script></body></html>`}
function overview(title,deck,kicker,cards){return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${deck}"><title>${title} · Embodied Forge</title><link rel="stylesheet" href="../styles.css"></head><body><header><div class="wrap nav"><a class="brand" href="../"><span>EF</span><div><b>EMBODIED FORGE</b><small>BY TALOSHUA</small></div></a><button class="menu">☰</button><nav><a href="../projects/">项目</a><a href="../knowledge/">知识库</a><a href="../insights/">论文与教程</a><a href="../resources/">工具与资源</a></nav></div></header><main><section class="page-hero"><div class="wrap"><p class="kicker">${kicker}</p><h1>${title}</h1><p>${deck}</p></div></section><section class="page-content wrap"><div class="entry-grid">${cards}</div></section></main><footer><div class="wrap"><a class="brand" href="../"><span>EF</span><div><b>EMBODIED FORGE</b></div></a><p>Robotics · Learning · Real-world Systems</p><small>© 2026 TalosHua</small></div></footer><script src="../app.js"></script></body></html>`}
const card=(type,title,text,href,meta='持续更新')=>`<article class="entry-card"><div class="entry-top"><span>${type}</span><b>${meta}</b></div><h2>${title}</h2><p>${text}</p><div class="entry-bottom"><small>Embodied Forge</small><a href="${href}">进入内容 →</a></div></article>`;
await mkdir(out,{recursive:true});await cp(join(root,'index.html'),join(out,'index.html'));await cp(join(root,'styles.css'),join(out,'styles.css'));await cp(join(root,'app.js'),join(out,'app.js'));await cp(join(root,'assets'),join(out,'assets'),{recursive:true});
async function walk(dir){for(const ent of await readdir(dir,{withFileTypes:true})){const p=join(dir,ent.name);if(ent.isDirectory())await walk(p);else if(ent.name.endsWith('.md')){const raw=await readFile(p,'utf8'),[meta,md]=front(raw),rel=p.slice(join(root,'content').length+1,-3),dest=join(out,rel,'index.html');await mkdir(dirname(dest),{recursive:true});await writeFile(dest,page(meta,parse(md)))}}}
await walk(join(root,'content'));await writeFile(join(out,'.nojekyll'),'');
const pages={
  projects:overview('项目','正在发生的机器人系统、训练方案和硬件工程。每个项目记录目标、架构、进展与真实世界验证。','PROJECTS',[
    card('RESEARCH · LOCOMOTION','仿生四足 Locomotion','自然步态、连续速度指令、动作模仿与 Sim2Real。','../projects/quadruped-locomotion/','IN PROGRESS'),
    card('HARDWARE · MANIPULATION','NexaArm','轻量桌面机械臂的结构、关节控制、通信与具身操作。','../projects/nexaarm/','PRIVATE'),
    card('ENGINEERING · CONTROL','多关节控制系统','面向执行器总线、状态机、安全控制和部署链路。','../projects/control-system/','OPEN SOURCE PLAN')
  ]),
  knowledge:overview('知识库','按机器人从感知到行动的完整链路，沉淀可以反复查阅的概念、方法与工程经验。','KNOWLEDGE MAP',[
    card('MOTION','Locomotion','步态、运动策略、地形适应与全身控制。','../topics/locomotion/'),card('LEARNING','Robot Learning','强化学习、模仿学习、VLA 与行为基础模型。','../topics/robot-learning/'),card('MANIPULATION','Manipulation','机械臂控制、灵巧操作与任务学习。','../topics/manipulation/'),card('SYSTEMS','Robot Hardware','执行器、CAN、EtherCAT 与嵌入式控制。','../topics/hardware/'),card('SENSING','Perception','深度视觉、高程图、定位与状态估计。','../topics/perception/'),card('TRANSFER','Embodied AI','把感知、决策和行动连接到真实世界。','../topics/embodied-ai/')
  ]),
  insights:overview('论文与教程','把值得拆解的研究、工程问题和机器人系统，整理成能直接读、能复用的内容。','READING & ENGINEERING',[
    card('论文解读','从 AMP 到行为基础模型','模仿学习、技能表征与生成式动作策略的技术路线。','../papers/amp-to-foundation-models/'),card('工程教程','CAN 多关节电机控制架构','从驱动板状态机到机器人主控的完整通信与控制链路。','../tutorials/can-multi-motor/'),card('系统拆解','MicroDuck：从硬件到软件','硬件、Rust 运行时、强化学习与 Sim2Real 如何闭环。','../analysis/microduck-full-stack/')
  ]),
  resources:overview('工具与资源','围绕机器人训练、仿真、执行器和开源工程持续整理的工具链与参考入口。','TOOLS & REFERENCES',[
    card('OPEN SOURCE','TalosHua on GitHub','代码、实验与持续更新的工程记录。','https://github.com/TalosHua','GITHUB'),card('SIMULATION','仿真与训练','MuJoCo、MJLab 与机器人强化学习工作流。','../topics/robot-learning/'),card('HARDWARE','硬件与执行器','电机、驱动、CAN、EtherCAT 与嵌入式控制参考。','../topics/hardware/'),card('READING','研究方向地图','从运动控制到具身智能的主题入口。','../knowledge/')
  ])
};
for(const [name,html] of Object.entries(pages)){const dest=join(out,name,'index.html');await mkdir(dirname(dest),{recursive:true});await writeFile(dest,html)}
console.log('Built Embodied Forge into _site');
