import {readdir,readFile,writeFile,mkdir,cp} from 'node:fs/promises';
import {join,dirname} from 'node:path';
const root=process.cwd(),out=join(root,'_site');
const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const inline=s=>s.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');
function parse(md){const lines=md.trim().split(/\r?\n/),html=[];let list=false,code=false,buf=[];const flush=()=>{if(buf.length){html.push(`<p>${inline(buf.join(' '))}</p>`);buf=[]}};for(const line of lines){if(line.startsWith('```')){if(code){html.push(`<pre><code>${esc(buf.join('\n'))}</code></pre>`);buf=[];code=false}else{flush();if(list){html.push('</ul>');list=false}code=true}continue}if(code){buf.push(line);continue}if(!line.trim()){flush();if(list){html.push('</ul>');list=false}continue}const h=line.match(/^(#{2,3})\s+(.+)/);if(h){flush();const level=h[1].length,id=h[2].toLowerCase().replace(/[^\w\u4e00-\u9fff]+/g,'-');html.push(`<h${level} id="${id}">${inline(h[2])}</h${level}>`);continue}if(line.startsWith('- ')){flush();if(!list){html.push('<ul>');list=true}html.push(`<li>${inline(line.slice(2))}</li>`);continue}if(line.startsWith('> ')){flush();html.push(`<blockquote>${inline(line.slice(2))}</blockquote>`);continue}buf.push(line)}if(code)html.push(`<pre><code>${esc(buf.join('\n'))}</code></pre>`);else flush();if(list)html.push('</ul>');return html.join('\n')}
function front(raw){const m=raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);if(!m)return [{},raw];const meta={};m[1].split('\n').forEach(l=>{const i=l.indexOf(':');if(i>0)meta[l.slice(0,i).trim()]=l.slice(i+1).trim()});return [meta,m[2]]}
function page(meta,body){const heads=[...body.matchAll(/<h2 id="([^"]+)">([^<]+)<\/h2>/g)];const toc=heads.map(x=>`<a href="#${x[1]}">${x[2]}</a>`).join('');return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${meta.description||meta.title}"><title>${meta.title} · Embodied Forge</title><link rel="stylesheet" href="../../styles.css"></head><body><header><div class="wrap nav"><a class="brand" href="../../"><span>EF</span><div><b>EMBODIED FORGE</b><small>BY TALOSHUA</small></div></a><button class="menu">☰</button><nav><a href="../../#projects">项目</a><a href="../../#knowledge">知识库</a><a href="../../#insights">论文与教程</a><a href="https://github.com/TalosHua">GitHub</a></nav></div></header><main class="article-shell wrap"><div class="article-head"><a class="back" href="../../">← 返回首页</a><div class="article-kicker">${meta.type||'NOTE'} · ${meta.status||'持续更新'}</div><h1>${meta.title}</h1><p class="article-deck">${meta.description||''}</p><div class="article-meta"><span>${meta.date||'2026-09-07'}</span><span>${meta.tags||''}</span><span>约 ${Math.max(3,Math.ceil(body.length/900))} 分钟阅读</span></div></div><div class="article-layout"><aside class="toc"><b>本页目录</b>${toc}</aside><article class="prose">${body}</article></div></main><footer><div class="wrap"><a class="brand" href="../../"><span>EF</span><div><b>EMBODIED FORGE</b></div></a><p>Robotics · Learning · Real-world Systems</p><small>© 2026 TalosHua</small></div></footer><script src="../../app.js"></script></body></html>`}
await mkdir(out,{recursive:true});await cp(join(root,'index.html'),join(out,'index.html'));await cp(join(root,'styles.css'),join(out,'styles.css'));await cp(join(root,'app.js'),join(out,'app.js'));await cp(join(root,'assets'),join(out,'assets'),{recursive:true});
async function walk(dir){for(const ent of await readdir(dir,{withFileTypes:true})){const p=join(dir,ent.name);if(ent.isDirectory())await walk(p);else if(ent.name.endsWith('.md')){const raw=await readFile(p,'utf8'),[meta,md]=front(raw),rel=p.slice(join(root,'content').length+1,-3),dest=join(out,rel,'index.html');await mkdir(dirname(dest),{recursive:true});await writeFile(dest,page(meta,parse(md)))}}}
await walk(join(root,'content'));await writeFile(join(out,'.nojekyll'),'');
console.log('Built Embodied Forge into _site');
